version: '3'

services:
  app:
    container_name: app
    hostname: app
    image: app:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGODB_URI="mongodb+srv://cachorro_cami:Tengo1amo@cluster0.ffbyjzl.mongodb.net/?retryWrites=true&w=majority"
    volumes:
      - ./app:/app
    restart: always
    expose:
      - 3000
    networks:
      - internal
      - external
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - 8080
    networks:
      - external
      - internal
  cloudflared:
    image: cloudflare/cloudflared:latest #update the verion where necessary
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - external
      - internal
    command:
      tunnel --no-autoupdate run --token
      eyJhIjoiZWQ2NmE1NDZlYWVhMWNlMDBlYjE2YmI1Yzc1NmFkY2EiLCJ0IjoiYzI2MmFhYTYtOTVkYi00YzE5LTk4NzktZTI2YzMwMTg1YmU4IiwicyI6Ik1HSTRNR05pT0RndE4ySXpNUzAwWWpjeUxUa3laakl0TmpZMll6WTBZMk16TVRSaiJ9
    volumes:
      - /opt/appdata/cloudflared/data:/home/nonroot/.cloudflared/

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  external:
    external: true
    name: external
  internal:
    external: true
    name: internal
